name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  google_sign_in: ^5.0.4
  flutter_signin_button: ^2.0.0
  animated_text_kit: ^4.2.1
  firebase_storage: ^9.0.0
  provider: ^5.0.0
  modal_progress_hud: ^0.1.3
  rflutter_alert: ^2.0.2
  cool_alert: ^1.1.0
  edge_alert: ^0.0.1
  salomon_bottom_bar: ^3.1.0
  font_awesome_flutter: ^9.2.0
  material_floating_search_bar: ^0.3.6
  uuid: ^3.0.5
  art_sweetalert: ^0.0.5
  flutter_gifimage: ^1.0.1
  expansion_tile_card: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  fonts:
    - family: Road Rage
      fonts:
        - asset: fonts/RoadRage-Regular.ttf